### ISSUE TITLE
Caught exception in launch (see debug for traceback): executable 'vmap_node' not found on the libexec directory '/home/user/tello_ros_ws/install/fiducial_vlam/lib/fiducial_vlam'

### ISSUE THREAD

**Issue by sunnysolution1618** [clydemcqueen/tello_ros#52]
Hi, thank you very much for sharing such a great project ~ 

It is very amazing ~

So far I tried tello_gazebo and it works very well ~

However, when I tried the integration of fiducial_vlam, it showed the following error:

```
user@ubuntu:~/tello_ros_ws$ ros2 launch tello_gazebo vlam_launch.py
[INFO] [launch]: All log files can be found below /home/user/.ros/log/2020-11-01-01-37-50-957820-ubuntu-9691
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'vmap_node' not found on the libexec directory '/home/user/tello_ros_ws/install/fiducial_vlam/lib/fiducial_vlam' 
Task exception was never retrieved
future: <Task finished coro=<LaunchService._process_one_event() done, defined at /opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py:293> exception=RuntimeError('Signal event received before subprocess transport available.',)>
Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 295, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 315, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/execute_process.py", line 383, in __on_signal_process_event
    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
[INFO] [gazebo-1]: process started with pid [9707]
[gazebo-1] [Msg] Waiting for master.
[gazebo-1] [Msg] Connected to gazebo master @ http://127.0.0.1:11345
[gazebo-1] [Msg] Publicized address: 192.168.142.135
[gazebo-1] Gazebo multi-robot simulator, version 9.14.0
[gazebo-1] Copyright (C) 2012 Open Source Robotics Foundation.
[gazebo-1] Released under the Apache 2 License.
[gazebo-1] http://gazebosim.org
[gazebo-1] 
[gazebo-1] Gazebo multi-robot simulator, version 9.14.0
[gazebo-1] Copyright (C) 2012 Open Source Robotics Foundation.
[gazebo-1] Released under the Apache 2 License.
[gazebo-1] http://gazebosim.org
[gazebo-1] 
[gazebo-1] [Wrn] [ModelDatabase.cc:340] Getting models from[http://models.gazebosim.org/]. This may take a few seconds.
[ERROR] [gazebo-1]: process[gazebo-1] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [gazebo-1]: sending signal 'SIGTERM' to process[gazebo-1]
[ERROR] [gazebo-1]: process has died [pid 9707, exit code -15, cmd 'gazebo --verbose -s libgazebo_ros_init.so -s libgazebo_ros_factory.so /home/user/tello_ros_ws/install/tello_gazebo/share/tello_gazebo/worlds/fiducial.world'].
[gazebo-1] 
[gazebo-1] 
user@ubuntu:~/tello_ros_ws$ 

```

Can I know what should I do in order to solve this ? 

Thank you very much .. 

Appreciate a lot ~

**Comment by clydemcqueen** [comment]
Thanks for reporting this bug. I just updated the launch file to use the new vlam node names. It should work now.
